import { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

import './globals.css';
import { ReactElement } from 'react';

import Providers from '^/components/Providers';
import Navbar from '^/components/Navbar';
import IBaseComponentProps from '^/types/IBaseComponentProps';

const font = Open_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app dark',
};

export default function RootLayout({
  children,
}: Readonly<Omit<IBaseComponentProps, 'className'>>): ReactElement {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          <Navbar />

          <div className="overflow-x-hidden">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
